name: Release Artifacts

on: workflow_dispatch

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            NAME: mac
          - os: ubuntu-latest
            NAME: linux
          - os: windows-latest
            NAME: windows

    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15
          cache: 'pnpm'

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.NAME == 'linux'
        run: >
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Install app dependencies and build it
        run: yarn && yarn build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
